### ISSUE TITLE
2 Errors 1 Question

### ISSUE THREAD

**Issue by Stanzilla** [Phanx/BetterArchaeologyUI#2]
When running https://github.com/Phanx/BetterArchaeologyUI/commit/adcc5902d46ff068afe531357e884b7a5988e061 I get

```
Error getting bonus fragments for Draenor Clans
Error getting bonus fragments for Arakkoa
```

on login. Also is the `Future Artifacts` panel just a placeholder for now or is it supposed to show all unfinished projects in this version? Only shows two for me.

**Comment by Stanzilla** [comment]
This error happens when you have fragments but not yet unlocked the archaeology "faction" on that character:

```
3x ...faceBetterArchaeologyUI\CurrentArtifacts.lua:291: attempt to compare nil with number
...faceBetterArchaeologyUI\CurrentArtifacts.lua:291: in function <...faceBetterArchaeologyUI\CurrentArtifacts.lua:266>
[C]: in function `UpdateFrame'
...ns\Blizzard_ArchaeologyUI\Blizzard_ArchaeologyUI.lua:615: in function <...ns\Blizzard_ArchaeologyUI\Blizzard_ArchaeologyUI.lua:554>
[C]: in function `ArchaeologyFrame_OnTabClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
[C]: in function `Click'
...ns\Blizzard_ArchaeologyUI\Blizzard_ArchaeologyUI.lua:121: in function <...ns\Blizzard_ArchaeologyUI\Blizzard_ArchaeologyUI.lua:111>
[C]: in function `Show'
FrameXML\UIParent.lua:2165: in function `SetUIPanel'
FrameXML\UIParent.lua:2009: in function `ShowUIPanel'
FrameXML\UIParent.lua:1880: in function <FrameXML\UIParent.lua:1876>
[C]: in function `SetAttribute'
...
[C]: ?
[C]: ?
[C]: in function `UseAction'
FrameXML\SecureTemplates.lua:348: in function `handler'
FrameXML\SecureTemplates.lua:649: in function <FrameXML\SecureTemplates.lua:597>
[C]: ?
FrameXML\SecureHandlers.lua:264: in function <FrameXML\SecureHandlers.lua:261>
[C]: ?
FrameXML\SecureHandlers.lua:294: in function <FrameXML\SecureHandlers.lua:277>
(tail call): ?

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> defined @Blizzard_ArchaeologyUI\Blizzard_ArchaeologyUI.lua:215
 = <function> defined @BetterArchaeologyUI\CurrentArtifacts.lua:266

```

**Comment by Phanx** [comment]
Please submit separate tickets for each issue. Also, please make sure you have the latest version before posting errors. Yes, the last commit didn't include any code changes, but it does mean that the line numbers in your stack traces are not very helpful and it's impossible for me to know exactly which line is triggering the error.

Re: the error in your second post, what exactly do you mean by this:

> you have fragments but not yet unlocked the archaeology "faction" on that character

?

**Comment by Stanzilla** [comment]
When you only get fragments via Garrison missions you never "uncover" the factions like you do when you actually do digsites, that means they don't show up in the Archaeology UI but you can collect fragments for them via missions etc.

**Comment by Cy4n1d3** [comment]
This happens for me aswell :)
Some of my characters have 1/75 in archaeology and only gathered fragments through missions.
