### ISSUE TITLE
getting a error

### ISSUE THREAD

**Issue by Saxitoxin** [Phanx/BetterArchaeologyUI#4]
2x ...ns\Blizzard_ArchaeologyUI\Blizzard_ArchaeologyUI.lua:186: attempt to call method 'UpdateFrame' (a nil value)
...ns\Blizzard_ArchaeologyUI\Blizzard_ArchaeologyUI.lua:186: in function <...ns\Blizzard_ArchaeologyUI\Blizzard_ArchaeologyUI.lua:150>

Locals:

**Comment by Phanx** [comment]
[More info, please.](http://phanx.net/addons/help#report)
